# Generated by Django 4.2.17 on 2024-12-27 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "tconst",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_adult", models.BooleanField(default=False)),
                ("year", models.CharField(blank=True, max_length=4, null=True)),
                ("end_year", models.CharField(blank=True, max_length=4, null=True)),
                ("runtime", models.CharField(blank=True, max_length=10, null=True)),
                ("genre", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "nconst",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("birth_year", models.CharField(blank=True, max_length=4, null=True)),
                ("death_year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "primary_professions",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("known_for_titles", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Principal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("job", models.CharField(blank=True, max_length=200, null=True)),
                ("characters", models.TextField(blank=True, null=True)),
                (
                    "nconst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.name"
                    ),
                ),
                (
                    "tconst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
            ],
        ),
    ]
