# Generated by Django 4.2.17 on 2024-12-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="principal",
            name="characters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
